// Major airlines for autocomplete
export const AIRLINES = [
  // US Airlines
  'American Airlines',
  'Delta Air Lines',
  'United Airlines',
  'Southwest Airlines',
  'Alaska Airlines',
  'JetBlue Airways',
  'Spirit Airlines',
  'Frontier Airlines',
  'Allegiant Air',
  'Sun Country Airlines',
  'Hawaiian Airlines',
  'Breeze Airways',

  // International Airlines
  'Air Canada',
  'British Airways',
  'Virgin Atlantic',
  'Air France',
  'KLM Royal Dutch Airlines',
  'Lufthansa',
  'Swiss International Air Lines',
  'Austrian Airlines',
  'Brussels Airlines',
  'Scandinavian Airlines (SAS)',
  'Finnair',
  'Icelandair',
  'Turkish Airlines',
  'Emirates',
  'Qatar Airways',
  'Etihad Airways',
  'Singapore Airlines',
  'Cathay Pacific',
  'Japan Airlines (JAL)',
  'All Nippon Airways (ANA)',
  'Korean Air',
  'Asiana Airlines',
  'Air China',
  'China Eastern Airlines',
  'China Southern Airlines',
  'Thai Airways',
  'Malaysia Airlines',
  'Qantas Airways',
  'Air New Zealand',
  'LATAM Airlines',
  'Avianca',
  'Copa Airlines',
  'Aeromexico',
  'WestJet',
  'Air Transat',
  'Iberia',
  'Vueling',
  'TAP Air Portugal',
  'Aer Lingus',
  'LOT Polish Airlines',
  'Norwegian Air',
  'Ryanair',
  'EasyJet',
];
