// Major airports with full names for autocomplete
export const AIRPORTS = [
  // Major US Airports
  { code: 'ATL', name: 'Atlanta (ATL)', city: 'Atlanta, GA' },
  { code: 'ORD', name: 'Chicago O\'Hare (ORD)', city: 'Chicago, IL' },
  { code: 'LAX', name: 'Los Angeles (LAX)', city: 'Los Angeles, CA' },
  { code: 'DFW', name: 'Dallas/Fort Worth (DFW)', city: 'Dallas, TX' },
  { code: 'DEN', name: 'Denver (DEN)', city: 'Denver, CO' },
  { code: 'JFK', name: 'New York JFK (JFK)', city: 'New York, NY' },
  { code: 'SFO', name: 'San Francisco (SFO)', city: 'San Francisco, CA' },
  { code: 'SEA', name: 'Seattle (SEA)', city: 'Seattle, WA' },
  { code: 'LAS', name: 'Las Vegas (LAS)', city: 'Las Vegas, NV' },
  { code: 'MCO', name: 'Orlando (MCO)', city: 'Orlando, FL' },
  { code: 'PHX', name: 'Phoenix (PHX)', city: 'Phoenix, AZ' },
  { code: 'IAH', name: 'Houston (IAH)', city: 'Houston, TX' },
  { code: 'MIA', name: 'Miami (MIA)', city: 'Miami, FL' },
  { code: 'BOS', name: 'Boston (BOS)', city: 'Boston, MA' },
  { code: 'MSP', name: 'Minneapolis (MSP)', city: 'Minneapolis, MN' },
  { code: 'DTW', name: 'Detroit (DTW)', city: 'Detroit, MI' },
  { code: 'PHL', name: 'Philadelphia (PHL)', city: 'Philadelphia, PA' },
  { code: 'LGA', name: 'New York LaGuardia (LGA)', city: 'New York, NY' },
  { code: 'EWR', name: 'Newark (EWR)', city: 'Newark, NJ' },
  { code: 'CLT', name: 'Charlotte (CLT)', city: 'Charlotte, NC' },
  { code: 'SAN', name: 'San Diego (SAN)', city: 'San Diego, CA' },
  { code: 'PDX', name: 'Portland (PDX)', city: 'Portland, OR' },
  { code: 'TPA', name: 'Tampa (TPA)', city: 'Tampa, FL' },
  { code: 'STL', name: 'St. Louis (STL)', city: 'St. Louis, MO' },
  { code: 'BWI', name: 'Baltimore (BWI)', city: 'Baltimore, MD' },
  { code: 'AUS', name: 'Austin (AUS)', city: 'Austin, TX' },
  { code: 'BNA', name: 'Nashville (BNA)', city: 'Nashville, TN' },
  { code: 'OAK', name: 'Oakland (OAK)', city: 'Oakland, CA' },
  { code: 'SJC', name: 'San Jose (SJC)', city: 'San Jose, CA' },
  { code: 'SAT', name: 'San Antonio (SAT)', city: 'San Antonio, TX' },
  { code: 'IAD', name: 'Washington Dulles (IAD)', city: 'Washington, DC' },
  { code: 'DCA', name: 'Washington Reagan (DCA)', city: 'Washington, DC' },
  { code: 'MDW', name: 'Chicago Midway (MDW)', city: 'Chicago, IL' },
  { code: 'HOU', name: 'Houston Hobby (HOU)', city: 'Houston, TX' },
  { code: 'DAL', name: 'Dallas Love Field (DAL)', city: 'Dallas, TX' },
  { code: 'SNA', name: 'Orange County (SNA)', city: 'Santa Ana, CA' },
  { code: 'SMF', name: 'Sacramento (SMF)', city: 'Sacramento, CA' },
  { code: 'RDU', name: 'Raleigh-Durham (RDU)', city: 'Raleigh, NC' },
  { code: 'IND', name: 'Indianapolis (IND)', city: 'Indianapolis, IN' },
  { code: 'MCI', name: 'Kansas City (MCI)', city: 'Kansas City, MO' },
  { code: 'CLE', name: 'Cleveland (CLE)', city: 'Cleveland, OH' },
  { code: 'PIT', name: 'Pittsburgh (PIT)', city: 'Pittsburgh, PA' },
  { code: 'CVG', name: 'Cincinnati (CVG)', city: 'Cincinnati, OH' },
  { code: 'CMH', name: 'Columbus (CMH)', city: 'Columbus, OH' },
  { code: 'MKE', name: 'Milwaukee (MKE)', city: 'Milwaukee, WI' },
  { code: 'MSY', name: 'New Orleans (MSY)', city: 'New Orleans, LA' },
  { code: 'RSW', name: 'Fort Myers (RSW)', city: 'Fort Myers, FL' },
  { code: 'PBI', name: 'West Palm Beach (PBI)', city: 'West Palm Beach, FL' },
  { code: 'FLL', name: 'Fort Lauderdale (FLL)', city: 'Fort Lauderdale, FL' },
  { code: 'BDL', name: 'Hartford (BDL)', city: 'Hartford, CT' },
  { code: 'PVD', name: 'Providence (PVD)', city: 'Providence, RI' },
  { code: 'SLC', name: 'Salt Lake City (SLC)', city: 'Salt Lake City, UT' },
  { code: 'ABQ', name: 'Albuquerque (ABQ)', city: 'Albuquerque, NM' },
  { code: 'ELP', name: 'El Paso (ELP)', city: 'El Paso, TX' },
  { code: 'TUS', name: 'Tucson (TUS)', city: 'Tucson, AZ' },
  { code: 'RNO', name: 'Reno (RNO)', city: 'Reno, NV' },
  { code: 'BUR', name: 'Burbank (BUR)', city: 'Burbank, CA' },
  { code: 'ONT', name: 'Ontario (ONT)', city: 'Ontario, CA' },
  { code: 'SJU', name: 'San Juan (SJU)', city: 'San Juan, PR' },
  { code: 'ANC', name: 'Anchorage (ANC)', city: 'Anchorage, AK' },
  { code: 'HNL', name: 'Honolulu (HNL)', city: 'Honolulu, HI' },
  { code: 'OGG', name: 'Maui (OGG)', city: 'Kahului, HI' },
  { code: 'LIH', name: 'Kauai (LIH)', city: 'Lihue, HI' },
  { code: 'KOA', name: 'Kona (KOA)', city: 'Kailua-Kona, HI' },
  { code: 'JAX', name: 'Jacksonville (JAX)', city: 'Jacksonville, FL' },
  { code: 'RIC', name: 'Richmond (RIC)', city: 'Richmond, VA' },
  { code: 'ORF', name: 'Norfolk (ORF)', city: 'Norfolk, VA' },
  { code: 'MHT', name: 'Manchester (MHT)', city: 'Manchester, NH' },
  { code: 'BUF', name: 'Buffalo (BUF)', city: 'Buffalo, NY' },
  { code: 'ROC', name: 'Rochester (ROC)', city: 'Rochester, NY' },
  { code: 'SYR', name: 'Syracuse (SYR)', city: 'Syracuse, NY' },
  { code: 'ALB', name: 'Albany (ALB)', city: 'Albany, NY' },
  { code: 'PWM', name: 'Portland (PWM)', city: 'Portland, ME' },
  { code: 'BTV', name: 'Burlington (BTV)', city: 'Burlington, VT' },
  { code: 'GSO', name: 'Greensboro (GSO)', city: 'Greensboro, NC' },
  { code: 'CHS', name: 'Charleston (CHS)', city: 'Charleston, SC' },
  { code: 'SAV', name: 'Savannah (SAV)', city: 'Savannah, GA' },
  { code: 'DSM', name: 'Des Moines (DSM)', city: 'Des Moines, IA' },
  { code: 'OMA', name: 'Omaha (OMA)', city: 'Omaha, NE' },
  { code: 'TUL', name: 'Tulsa (TUL)', city: 'Tulsa, OK' },
  { code: 'OKC', name: 'Oklahoma City (OKC)', city: 'Oklahoma City, OK' },
  { code: 'ICT', name: 'Wichita (ICT)', city: 'Wichita, KS' },
  { code: 'LIT', name: 'Little Rock (LIT)', city: 'Little Rock, AR' },
  { code: 'MEM', name: 'Memphis (MEM)', city: 'Memphis, TN' },
  { code: 'BHM', name: 'Birmingham (BHM)', city: 'Birmingham, AL' },
  { code: 'JAC', name: 'Jackson Hole (JAC)', city: 'Jackson, WY' },
  { code: 'BOI', name: 'Boise (BOI)', city: 'Boise, ID' },
  { code: 'GEG', name: 'Spokane (GEG)', city: 'Spokane, WA' },
  { code: 'FAT', name: 'Fresno (FAT)', city: 'Fresno, CA' },

  // International
  { code: 'LHR', name: 'London Heathrow (LHR)', city: 'London, UK' },
  { code: 'LGW', name: 'London Gatwick (LGW)', city: 'London, UK' },
  { code: 'CDG', name: 'Paris Charles de Gaulle (CDG)', city: 'Paris, France' },
  { code: 'FRA', name: 'Frankfurt (FRA)', city: 'Frankfurt, Germany' },
  { code: 'AMS', name: 'Amsterdam (AMS)', city: 'Amsterdam, Netherlands' },
  { code: 'MAD', name: 'Madrid (MAD)', city: 'Madrid, Spain' },
  { code: 'BCN', name: 'Barcelona (BCN)', city: 'Barcelona, Spain' },
  { code: 'FCO', name: 'Rome (FCO)', city: 'Rome, Italy' },
  { code: 'DUB', name: 'Dublin (DUB)', city: 'Dublin, Ireland' },
  { code: 'ZRH', name: 'Zurich (ZRH)', city: 'Zurich, Switzerland' },
  { code: 'YYZ', name: 'Toronto (YYZ)', city: 'Toronto, Canada' },
  { code: 'YVR', name: 'Vancouver (YVR)', city: 'Vancouver, Canada' },
  { code: 'YUL', name: 'Montreal (YUL)', city: 'Montreal, Canada' },
  { code: 'MEX', name: 'Mexico City (MEX)', city: 'Mexico City, Mexico' },
  { code: 'CUN', name: 'Cancun (CUN)', city: 'Cancun, Mexico' },
  { code: 'GRU', name: 'São Paulo (GRU)', city: 'São Paulo, Brazil' },
  { code: 'NRT', name: 'Tokyo Narita (NRT)', city: 'Tokyo, Japan' },
  { code: 'HND', name: 'Tokyo Haneda (HND)', city: 'Tokyo, Japan' },
  { code: 'ICN', name: 'Seoul (ICN)', city: 'Seoul, South Korea' },
  { code: 'HKG', name: 'Hong Kong (HKG)', city: 'Hong Kong' },
  { code: 'SIN', name: 'Singapore (SIN)', city: 'Singapore' },
  { code: 'DXB', name: 'Dubai (DXB)', city: 'Dubai, UAE' },
  { code: 'DOH', name: 'Doha (DOH)', city: 'Doha, Qatar' },
  { code: 'SYD', name: 'Sydney (SYD)', city: 'Sydney, Australia' },
  { code: 'MEL', name: 'Melbourne (MEL)', city: 'Melbourne, Australia' },
];
